# Generated by Django 5.0.3 on 2024-03-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=20)),
                ('parent_name', models.CharField(max_length=20)),
                ('dob', models.DateField(auto_now=True)),
                ('gender', models.CharField(choices=[('BOY', 'boy'), ('GIRL', 'girl'), ('OTHER', 'other')], max_length=10)),
                ('home_address', models.CharField(max_length=50)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
        ),
    ]
